/* Auto generated file by build envsetup shell.
 !!!!!!!! Do not edit this file. !!!!!!!!
 Created time : Thu Apr 10 20:43:01 KST 2014
TARGET_BUILD_BOARDVER : tp20
*/

#define CONFIG_BOARD_VER CONFIG_TP20

